@startuml
'https://plantuml.com/sequence-diagram

autonumber

header System sekvens diagram
actor Bruger
  Bruger <-- System: Startscreen

  alt Treament
      Bruger -> System: Treatment
      Bruger <-- System: Shows Treaments
      Bruger -> System: Book Treatment
      Bruger <-- System: CustomerLoginScreen
  end

alt Customer

    Bruger -> System: Customer
    Bruger <-- System: CustomerLoginScreen

    alt Existing Customer
        Bruger -> System: Type number
        Bruger -> System: Login pressed
        Bruger <-- System: Shows Appointment
    else New Customer
        Bruger -> System: Create Account
        Bruger -> System: Type details
        Bruger <-- System: Account created

    end

end

alt Employee
    Bruger -> System: Employee
    Bruger <-- System: EmployeeLoginScreen
    Bruger -> System: Type logindetails
     Bruger -> System: Login pressed
    Bruger <-- System: Shows Appointment
end


Bruger -> System: Set Dato
Bruger -> System: Set Employee
Bruger -> System: Create appointment
Bruger <-- System: Appointment created

@enduml