@startuml
'https://plantuml.com/sequence-diagram

autonumber

header System sekvens diagram
actor Bruger

alt Customer

    Bruger -> System: Customer
    Bruger <-- System: CustomerLoginScreen

    alt Existing Customer
        Bruger -> System: Skriver nummer
        Bruger <-- System: Viser Appointment
    else New Customer
        Bruger -> System: Create Account
        Bruger -> System: Skriver detaljerne
        Bruger <-- System: Account created

    end

end

alt Employee
    Bruger -> System: Employee
    Bruger <-- System: EmployeeLoginScreen
    Bruger -> System: Skriver logindetails
    Bruger <-- System: Viser Appointment
end


Bruger -> System: Set Dato
Bruger -> System: Set Employee
Bruger -> System: Create appointment
Bruger <-- System: Appointment created

@enduml